'use strict';

//DOM selector
const htmlBgColor = document.querySelector('body');
const btnAgain = document.querySelector('.again');
const btnCheck = document.querySelector('.check');
const numberBox = document.querySelector('.number');
const messageBox = document.querySelector('.message');
const scoreBox = document.querySelector('.score');
const highscoreBox = document.querySelector('.highscore');

//Initiliaze value
let score = 20;
let highScore = 0;
let playerWin = false;
//Generated by generateGuessNumber function
let numberToGuess = generateGuessNumber();

btnCheck.addEventListener('click', () => {
  //Input field for guessing the number
  const guessNumber = parseInt(document.querySelector('.guess').value);

  checkGuessNumber(guessNumber);
});

btnAgain.addEventListener('click', () => {
  restartGame();
});

const checkGuessNumber = function (guess) {
  let str = '';

  // If number is not a true value
  if (!guess) {
    displayMessage('🙄 No number');
    //When player wins
  } else if (numberToGuess === guess) {
    playerWin = true;
    displayMessage('🎉 You got the correct number!');
    updateUI();
    updateNumberBox(numberToGuess);
    updateHighScore(score);

    //When guess is wrong
  } else if (numberToGuess !== guess) {
    if (score > 1) {
      updateScore();
      displayMessage(guess > numberToGuess ? '📈 Too high!' : '📉 Too low!');
    } else {
      updateScore();
      displayMessage('💥 Game Over! ');
    }
  }
};

const displayMessage = msg => {
  messageBox.textContent = msg;
};

const updateUI = () => {
  if (playerWin) {
    htmlBgColor.style.backgroundColor = '#60b347';
    numberBox.style.width = '30rem';
    btnCheck.disabled = true;
    playerWin = false;
  } else {
    htmlBgColor.style.backgroundColor = '#222';
    numberBox.style.width = '15rem';
    btnCheck.disabled = false;
  }
};

const updateScore = () => {
  if (score === 0) {
    scoreBox.textContent = 0;
  } else {
    score--;
    scoreBox.textContent = score;
  }
};

const updateHighScore = score => {
  if (score > highScore) {
    highScore = score;
    highscoreBox.textContent = score;
  }
};

const updateNumberBox = num => (numberBox.textContent = num);

const restartGame = () => {
  //Reset UI
  updateUI();
  //New Number to Guess
  numberToGuess = generateGuessNumber();
  //Reset Score
  scoreBox.textContent = resetScore();
  //Reset Input Field
  const guessNumber = (document.querySelector('.guess').value = '');
  //Reset Message Content
  messageBox.textContent = 'Start guessing...';
  //Reset Number to Guess Container
  numberBox.textContent = '?';
};

const resetScore = () => (score = 20);

function generateGuessNumber() {
  const secretNumber = Math.trunc(Math.random() * 20 + 1);
  console.log(`Number to Guess is ${secretNumber}`);
  return secretNumber;
}
